### ISSUE TITLE
Set Payment brand to something other than IDEAL

### ISSUE THREAD

**Issue by joshi-priyanka** [janssenr/RaboOmniKassaApi.Net#3]
Does this work with a different payment method, other than IDEAL? I set the following:

MerchantOrder order = new MerchantOrder()
            {
                MerchantOrderId = OrderID + "x" + DateTime.Now.ToString("hhmmss"),
                Description = "",
                Amount = GetAmount(double.Parse(Amount)),
                CustomerInformation = new CustomerInformation(),
                Language = LanguageCode,
                MerchantReturnUrl = ReturnUrl,
                Signature = SigningKey_TEST,
                PaymentBrand = PaymentBrand.Maestro,
                PaymentBrandForce = PaymentBrandForce.ForceOnce
            };

This threw the following exception:

"order could not be restricted to MAESTRO, POI with id 44673 can only be restricted to payment brands: IDEAL."

**Comment by janssenr** [comment]
Are you sure you ae using the SANDBOX RefreshToken and SigningKey?
Because it should work on the SANDBOX environment.
In the PRODUCTION environment it is depending on which payment methods are configured for your account (POI).
So it looks like you are using the PRODUCTION environment.

NOTE: You should NOT set the "MerchantOrder.Signature" property.
It is calculated when you send the request.

**Comment by joshi-priyanka** [comment]
I was working on Production environment, and changed the signature key to Production key.  I will check for the allowed payment methods in the account.

Thanks.
